Repository rohansx/informatician, pull requests merged in 2023-07, with the labels that each got.

#762 navbar upload book icon fixed
  src/components/Navbar/NavItems/NavItems.js
Labels: level1, gssoc23

#759 The profile pictures of the contributors are now redirecting to their GitHub pages
  src/components/Home/BkCards/BkCards.css
  src/components/Home/BkCards/BkCards.js
  src/components/Home/CgCards/CardContent/CardContent.css
  src/components/Home/CgCards/CardContent/CardContent.js
  src/components/Home/CgCards/CgCards.js
  src/components/Home/Home.js
  src/components/Team/ContCard.js
  src/components/Team/Contributor.js
  src/components/Team/Team.js
Labels: level2, gssoc23

#758 Add Responsiveness to Biography Page
  src/components/Categories/biography.css
  src/components/Categories/biography.js
  src/components/Home/CgCards/CardContent/CardContent.js
Labels: bug, level1, gssoc23

#767 Added proper meta tags
  public/index.html
Labels: level2, gssoc23

#769 Awards Page
  src/assets/awards/manbooker.webp
  src/assets/awards/national.webp
  src/assets/awards/pen-faulkner.webp
  src/assets/awards/pulitzer.webp
  src/assets/awards/womenprize.webp
  src/components/Body.js
  src/components/Footer/Footer.js
  src/pages/Awards/BookAwards.css
  src/pages/Awards/BookAwards.js
Labels: level2, gssoc23

#771 Added dark mode for /addBooks page and changes in card border
  package-lock.json
  src/components/AddBooks/AddBooks.css
  src/components/AddBooks/AddBooks.js
  src/components/AddBooks/Upload.css
  src/components/Body.js
  src/components/Cards/Card.css
  src/components/Home/BkCards/CardContent/CardContent.js
Labels: level3

#777 Proper alt attribute added
  src/components/About/Download.js
  src/components/BookList/BookList.js
  src/components/Error/Error.js
  src/components/FAQ/faq.js
  src/components/Home/SingleBk/SingleBk.js
  src/components/Home/SingleBk/SingleBk1.js
  src/components/Home/SingleBk/SingleBk10.js
  src/components/Home/SingleBk/SingleBk11.js
  src/components/Home/SingleBk/SingleBk12.js
  src/components/Home/SingleBk/SingleBk13.js
  src/components/Home/SingleBk/SingleBk14.js
  src/components/Home/SingleBk/SingleBk2.js
  src/components/Home/SingleBk/SingleBk3.js
  src/components/Home/SingleBk/SingleBk4.js
  src/components/Home/SingleBk/SingleBk5.js
  src/components/Home/SingleBk/SingleBk6.js
  src/components/Home/SingleBk/SingleBk7.js
  src/components/Home/SingleBk/SingleBk8.js
  src/components/Home/SingleBk/SingleBk9.js
  src/components/Navbar/NavItems/NavItems.js
  src/components/Team/Team.js
  src/pages/About/About.js
  src/pages/Awards/BookAwards.js
  src/pages/Benefits/Benefits.js
  src/pages/BookFormats/BookFormats.js
  src/pages/Bookmarks/BookmarkPage.js
  src/pages/Contact/Contactus.js
  src/pages/Develop/develop.js
  src/pages/GenreDetails/GenreDetails.js
  src/pages/JoinOurTeam/Join.js
Labels: level2, gssoc23

#781 Added contributors list in about page
  package-lock.json
  src/components/About/Contributors.js
  src/pages/About/About.js
Labels: level2, gssoc23

#765 Added Newsletter below the logo
  src/components/Footer/Footer.js
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Footer/NewsLetter/NewsLetter.js
Labels: level1, gssoc23

#789 Smooth card hovering
  src/components/Home/BkCards/BkCards.css
  src/components/Home/BkCards/CardContent/CardContent.css
Labels: level2, gssoc23

#792 Benefits page ui fixes
  package-lock.json
  src/pages/Benefits/Benefits.css
  src/pages/Benefits/Benefits.js
Labels: level2, gssoc23

#793 implementing footer and newsletter
  src/app/layout.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Footer/NewsLetter/NewsLetter.js
Labels: level3, gssoc23

#795 Added context styles folder
  context/DataProvider.js
  src/app/layout.js
  src/components/Client.js
  src/components/Footer/Footer.js
  src/components/Footer/NewsLetter/NewsLetter.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/styles/globals.css
  tailwind.config.js
Labels: level2, gssoc23

#794 added hover effect
  package-lock.json
  package.json
  src/pages/About/About.js
Labels: level2, gssoc23

#796 Added more features
  Added more features
Labels: level1, gssoc23

#797 fixing deployment errors & removing unnecessary code
  app/favicon.ico
  app/globals.css
  app/layout.js
  app/page.js
  components/Footer/Footer.css
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.css
  components/Footer/NewsLetter/NewsLetter.js
  components/Navbar/NavItems/NavItems.js
  components/Navbar/Navbar.css
  components/Navbar/Navbar.js
  jsconfig.json
  src/components/Client.js
  styles/globals.css
  tailwind.config.js
Labels: level2, gssoc23

#806 Fix SlideBars
  src/components/Home/BkCards/BkCards.css
  src/components/Home/BkCards/BkCards.js
Labels: level1, gssoc23

#808 Working home components
  Added more features
  app/favicon.ico
  app/layout.js
  app/layout.jsx
  app/page.jsx
  components/Hero/CgCards/CardContent/CardContent.css
  components/Hero/CgCards/CardContent/CardContent.jsx
  components/Hero/CgCards/CgCards.jsx
  components/Hero/Hero.jsx
  components/Hero/ImgSection/ImgSection.css
  components/Hero/ImgSection/ImgSection.js
  next.config.js
  package-lock.json
  package.json
  src/pages/About/About.js
  src/pages/Benefits/Benefits.css
  src/pages/Benefits/Benefits.js
Labels: level3, gssoc23

#802 hover effect enhancement done in the footer section
  src/components/Footer/Footer.css
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Footer/NewsLetter/NewsLetter.js
Labels: level1, gssoc23

#818 fixing erros while deploying and the image section in home page
  app/layout.jsx
  app/page.jsx
  components/Hero/ImgSection/AutoType.jsx
  components/Hero/ImgSection/ImgSection.css
  components/Hero/ImgSection/ImgSection.js
  components/Navbar/Navbar.js
  next.config.js
  package-lock.json
  package.json
  src/pages/About/About.js
  src/pages/Benefits/Benefits.css
  src/pages/Benefits/Benefits.js
Labels: level2, gssoc23

#834 Solved Features Card Responsive & Overflowing issue for all devices
  src/components/About/Feature.css
Labels: level1, gssoc23

#833 Alignment of download buttons have been fixed
  src/components/About/Download.js
Labels: level1, gssoc23

#832 feat: add slider to quote section
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
Labels: level2, gssoc23

#830 [FEAT]: MAKE SOCIAL ANCHORS ACCESSIBLE ON FOOTER ✨
  src/components/Footer.js
Labels: level1, gssoc23

#820 added toast errors
  src/components/Footer/NewsLetter/NewsLetter.js
  src/components/Newsletter.js
  src/pages/Contact/Contactus.js
Labels: level1, gssoc23

#835 adding about page in website
  app/about/About.css
  app/about/page.jsx
  app/layout.jsx
  components/About/Download.css
  components/About/Download.js
  components/About/Feature.css
  components/About/Feature.js
  components/About/Testimonial.css
  components/About/Testimonial.js
  components/Footer/NewsLetter/NewsLetter.css
  components/Footer/NewsLetter/NewsLetter.js
  components/ScrollButton/ScrollButton.css
  components/ScrollButton/ScrollButton.js
Labels: level2, gssoc23

#798 Redesign footer
  src/components/Footer.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Footer/NewsLetter/NewsLetter.js
Labels: level2, gssoc23

#841 bkCards Code Refactor
  src/components/Home/BkCards/BkCards.js
  src/components/Home/BkCards/Books.js
Labels: level1, gssoc23

#829 Working home components: Added Styling into the hero component
  app/layout.jsx
  app/page.jsx
  components/DataProvider.js
  components/Hero/CgCards/CgCards.jsx
  components/Hero/Hero.jsx
  components/Hero/ImgSection/ImgSection.css
  next.config.js
  tailwind.config.js
Labels: level2, gssoc23

#845 fixing errors in contact page and optimizing it
  app/contact/page.jsx
Labels: level1, gssoc23

#846 Added Books Page also added ScrollToTopButton Component
  app/books/page.jsx
  components/BkCards/BkCards.css
  components/BkCards/BkCards.js
  components/BkCards/CardContent/CardContent.css
  components/BkCards/CardContent/CardContent.js
  components/Hero/CgCards/CardContent/CardContent.jsx
  components/Hero/CgCards/CgCards.jsx
  components/Hero/Hero.jsx
  next.config.js
  styles/Booklist.module.css
  styles/CardContent.module.css
  styles/ScrollButton.module.css
Labels: level3, gssoc23

#848 feat : Create Lock.yml ✔
  .github/workflows/lock.yml
Labels: level1, gssoc23

#850 Hover effect of Github logo has been updated
  src/components/Footer/Footer.js
  src/components/Home/CgCards/CardContent/CardContent.css
  src/components/Home/CgCards/CardContent/CardContent.js
Labels: level1, gssoc23

#852 Added text color to the FAQ section in light mode issue-843
  src/components/FAQ/faq.css
Labels: level1, gssoc23

#855 Added the file and fixed the loading issue in server side componets
  package-lock.json
  package.json
  public/index.html
  src/components/Body.js
  src/components/Loader/loader.css
  src/components/Loader/loader.js
Labels: level2, gssoc23

#849 mail functionality - PR conflicts #819, issue #774
  server/app.js
  server/package-lock.json
  server/package.json
  src/components/Newsletter.js
Labels: level2, gssoc23

#859 adding our team page
  app/team/Contributors.js
  app/team/Team.css
  app/team/page.jsx
Labels: level2, gssoc23

#861 fixing errors and deleting unnecessary file
  app/books/page.jsx
  styles/Booklist.module.css
  styles/ScrollButton.module.css
Labels: level2, gssoc23

#862 adding accessibility page
  app/accessibility/Accessibility.css
  app/accessibility/page.js
Labels: level2, gssoc23

#863 Fixing All issues by adding eslint config
  .eslintrc.json
  components/Hero/Hero.jsx
  package-lock.json
  package.json
Labels: level3, gssoc23

#866 adding awards page
  app/awards/BookAwards.css
  app/awards/page.js
Labels: level2, gssoc23

#857 Update: Fixed codebase for /books/:id
  src/assets/ebooks/ebk7.webp
  src/assets/ebooks/ebk8.webp
  src/components/Body.js
  src/components/Home/BkCards/BkCards.js
  src/components/Home/BkCards/Books.js
  src/components/Home/BkCards/CardContent/CardContent.css
  src/components/Home/BkCards/CardContent/CardContent.js
  src/components/Home/BookComponent/BookComponent.css
  src/components/Home/BookComponent/BookComponent.js
  src/components/Home/Books.js
  src/components/Home/CgCards/CgCards.js
  src/components/Home/Home.js
  src/components/Home/ImgSection/ImgSection.js
  src/components/Home/SingleBk/SingleBk.css
  src/components/Home/SingleBk/SingleBk.js
  src/components/Home/SingleBk/SingleBk1.js
  src/components/Home/SingleBk/SingleBk10.js
  src/components/Home/SingleBk/SingleBk11.js
  src/components/Home/SingleBk/SingleBk12.js
  src/components/Home/SingleBk/SingleBk13.js
  src/components/Home/SingleBk/SingleBk14.js
  src/components/Home/SingleBk/SingleBk2.js
  src/components/Home/SingleBk/SingleBk3.js
  src/components/Home/SingleBk/SingleBk4.js
  src/components/Home/SingleBk/SingleBk5.js
  src/components/Home/SingleBk/SingleBk6.js
  src/components/Home/SingleBk/SingleBk7.js
  src/components/Home/SingleBk/SingleBk8.js
  src/components/Home/SingleBk/SingleBk9.js
  src/pages/Bookmarks/BookmarkPage.js
Labels: level3, gssoc23

#864 Logo On About Page Changed
  src/assets/logos/darklogo_png.png
  src/assets/logos/logo_png.png
  src/components/About/Download.css
  src/components/About/Download.js
  src/pages/About/About.js
Labels: level1, gssoc23

#868 adding book-format page
  app/formats/BookFormats.css
  app/formats/page.js
Labels: level2, gssoc23

#871 adding cookie policy page
  app/cookie/Cookie.css
  app/cookie/page.js
Labels: level1, gssoc23

#872 adding copyright page
  app/copyright/Copyright.css
  app/copyright/page.js
Labels: level1, gssoc23

#873 adding genre details page
  app/genre/GenreDetails.css
  app/genre/page.js
Labels: level1, gssoc23

#874 adding join our team page
  app/join/page.js
  app/join/quotationmark.webp
  app/join/workinginoffice.webp
  app/join/workplace.jpeg
  next.config.js
Labels: level1, gssoc23

#875 adding privacy policy page
  app/privacy/PrivacyPolicy.css
  app/privacy/page.js
Labels: level1, gssoc23

#876 adding publishers page for nextjs
  app/publishers/Publishers.css
  app/publishers/page.jsx
Labels: level1, gssoc23

#898 Fix: Navbar
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Footer/NewsLetter/NewsLetter.js
  src/utils/searchBooks.js
Labels: level2, gssoc23

#883 Content of all the genres
  src/components/Categories/biography.js
  src/components/Categories/career.js
  src/components/Categories/component/Card.js
  src/components/Categories/contemporary.js
  src/components/Categories/cooking.js
  src/components/Categories/garden.js
  src/components/Categories/index.css
  src/components/Categories/mystery.js
  src/components/Categories/politics.js
  src/components/Categories/science.js
  src/components/Categories/selfhelp.js
  src/components/Categories/travel.js
Labels: level2, gssoc23

#877 adding terms page
  app/terms/TermsAndService.css
  app/terms/page.js
Labels: level1, gssoc23

#879 adding faq page
  app/faq/faq.css
  app/faq/page.js
Labels: level1, gssoc23

#902 Create lint.yml
  .github/workflows/lint.yml
Labels: level1, gssoc23

#880 adding pcategories pages
  app/pcategories/biography/biography.css
  app/pcategories/biography/page.js
  app/pcategories/career/page.js
  app/pcategories/contemporary/page.js
  app/pcategories/cooking/page.js
  app/pcategories/garden/page.js
  app/pcategories/mystery/page.js
  app/pcategories/politics/page.js
  app/pcategories/science/page.js
  app/pcategories/selfhelp/page.js
  app/pcategories/travel/page.js
  components/Home/BkCards/BkCards.css
  components/Home/BkCards/BkCards.js
  components/Home/BkCards/Books.js
  components/Home/BkCards/CardContent/CardContent.css
  components/Home/BkCards/CardContent/CardContent.js
  components/Home/CgCards/CardContent/CardContent.css
  components/Home/CgCards/CardContent/CardContent.js
  components/Home/CgCards/CgCards.js
  components/Home/Home.js
  components/Home/ImgSection/ImgSection.css
  components/Home/ImgSection/ImgSection.js
  components/Home/SingleBk/SingleBk.css
  components/Home/SingleBk/SingleBk.js
  components/Home/SingleBk/SingleBk1.js
  components/Home/SingleBk/SingleBk10.js
  components/Home/SingleBk/SingleBk11.js
  components/Home/SingleBk/SingleBk12.js
  components/Home/SingleBk/SingleBk13.js
  components/Home/SingleBk/SingleBk14.js
  components/Home/SingleBk/SingleBk2.js
  components/Home/SingleBk/SingleBk3.js
  components/Home/SingleBk/SingleBk4.js
  components/Home/SingleBk/SingleBk5.js
  components/Home/SingleBk/SingleBk6.js
  components/Home/SingleBk/SingleBk7.js
  components/Home/SingleBk/SingleBk8.js
  components/Home/SingleBk/SingleBk9.js
Labels: level2, gssoc23

#907 css issue fix for subscribe button and email id bug no:- #895
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Newsletter.js
Labels: level1, gssoc23

#912 changed color of headings on home page
  src/components/Home/BkCards/BkCards.css
  src/components/Home/BkCards/BkCards.js
  src/components/Home/CgCards/CgCards.js
  src/components/Home/Home.js
Labels: level1, gssoc23

#909 Update readme.md with website link
  readme.md
Labels: level1, gssoc23

#891 Adding AdChoice Page & Develop Page
  app/adchoices/page.jsx
  app/books/page.jsx
  app/develop/develop.css
  app/develop/page.jsx
  app/success/page.jsx
  components/Error/Error.js
  styles/AdChoices.module.css
  styles/Error.module.css
  styles/globals.css
Labels: bug, level2, gssoc23

#958 Server side middleware is added
  server/middleware/auth.middlware.js
  server/package-lock.json
  server/package.json
  server/router/book.js
  server/router/contact.js
  server/router/newsletter.js
Labels: level2, gssoc23

#919 Made headings visible
  src/components/About/Contributors.js
  src/components/AddBooks/Upload.js
  src/components/Home/BookComponent/BookComponent.css
Labels: level1, gssoc23

#935 adding sections in home page
  app/page.jsx
  app/pcategories/biography/biography.css
  app/pcategories/biography/page.js
  components/Hero/CgCards/CardContent/CardContent.jsx
  components/Hero/CgCards/CgCards.jsx
  components/Hero/Hero.jsx
  components/Hero/ImgSection/ImgSection.css
  components/Hero/ImgSection/ImgSection.js
  components/Home/BkCards/BkCards.css
  components/Home/BkCards/BkCards.js
  components/Home/BkCards/Books.js
  components/Home/BkCards/CardContent/CardContent.css
  components/Home/BkCards/CardContent/CardContent.js
  components/Home/BookComponent/BookComponent.css
  components/Home/BookComponent/BookComponent.js
  components/Home/Books.js
  components/Home/CgCards/CardContent/CardContent.js
  components/Home/CgCards/CgCards.js
  components/Home/Home.js
  components/Home/ImgSection/AutoType.jsx
  components/Home/ImgSection/ImgSection.css
  components/Home/ImgSection/ImgSection.js
  components/Home/SingleBk/SingleBk.css
  components/Home/SingleBk/SingleBk.js
  components/Home/SingleBk/SingleBk1.js
  components/Home/SingleBk/SingleBk10.js
  components/Home/SingleBk/SingleBk11.js
  components/Home/SingleBk/SingleBk12.js
  components/Home/SingleBk/SingleBk13.js
  components/Home/SingleBk/SingleBk14.js
  components/Home/SingleBk/SingleBk2.js
  components/Home/SingleBk/SingleBk3.js
  components/Home/SingleBk/SingleBk4.js
  components/Home/SingleBk/SingleBk5.js
  components/Home/SingleBk/SingleBk6.js
  components/Home/SingleBk/SingleBk7.js
  components/Home/SingleBk/SingleBk8.js
  components/Home/SingleBk/SingleBk9.js
  public/assets/ebooks/ebk7.webp
  public/assets/ebooks/ebk8.webp
  public/assets/logos/darklogo_png.png
  public/assets/logos/logo_png.png
  public/index.html
Labels: level3, gssoc23

#911 fixed card text center
  src/components/Home/CgCards/CardContent/CardContent.js
Labels: level1, gssoc23

#941 Added ARIA attributes to contact us form
  src/pages/Contact/Contactus.js
Labels: level1, gssoc23

#963 adding single book page by dynamic routing
  app/books/Books.js
  app/books/[id]/bookComponent.css
  app/books/[id]/page.jsx
  app/books/book/1/page.jsx
  app/books/book/2/page.jsx
  app/books/book/page.jsx
  package-lock.json
  package.json
Labels: level3, gssoc23

#969 adding metadata in website and updating the packages version
  app/layout.jsx
  package-lock.json
  package.json
Labels: level2, gssoc23

#989 converting about, accessibility and adchoice page in tailwindcss and …
  app/about/About.css
  app/about/page.jsx
  app/accessibility/Accessibility.css
  app/accessibility/page.js
  app/accessibility/page.jsx
  app/adchoices/page.jsx
  app/layout.jsx
  components/About/Feature.js
  components/About/Testimonial.css
  components/About/Testimonial.js
  styles/AdChoices.module.css
Labels: level2, gssoc23

#952 Pages styles aesthetic
  src/pages/Accessibility/Accessibility.css
  src/pages/AdChoices/AdChoices.css
  src/pages/Cookies/Cookie.css
  src/pages/Copyright/Copyright.css
  src/pages/Privacy/PrivacyPolicy.css
  src/pages/Publishers/Publishers.css
  src/pages/Terms/TermsAndService.css
Labels: level2, gssoc23

#992 Fixing 2 errors in backend
  app/api/book/[id]/route.js
  app/api/book/category/route.js
  app/api/book/new/route.js
  app/api/book/route.js
Labels: level1, gssoc23

#995 Added Newsletter & Mail API Routes
  app/api/mail/route.js
  app/api/newsletter/route.js
  app/api/newsletter/user/route.js
  package-lock.json
Labels: level3, gssoc23

#997 converting awards, benefits and contact page css to tailwindcss and optimizing the code
  app/awards/BookAwards.css
  app/awards/bookAwardsData.js
  app/awards/page.js
  app/benefits/Benefits.css
  app/benefits/page.js
  app/contact/page.jsx
  package-lock.json
  package.json
  styles/Contact.module.css
Labels: level2, gssoc23

#923 Features Cards Ui
  src/components/About/Feature.css
  src/components/About/Feature.js
Labels: level2, gssoc23

#925 css Fix for navbar bug no :- 921
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.js
Labels: level1, gssoc23

#927 Quotes cards in Dark mode
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
Labels: level1, gssoc23

#942 Create comment-on-PR.yml
  .github/workflows/comment-on-PR.yml
Labels: level2, gssoc23

#945 Font color of the Heading have been changed
  src/components/About/Download.js
  src/components/About/Feature.js
  src/pages/About/About.js
Labels: level1, gssoc23

#968 Added Search Functionality to Books Page
  src/components/BookList/BookCard.css
  src/components/BookList/BookCard.js
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
Labels: level2, gssoc23

#977 Fixes: pages not auto scrolling to top issue
  src/components/Body.js
Labels: level1, gssoc23

#980 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc23

#985 Proper Routing of categories
  src/components/Home/CgCards/CardContent/CardContent.js
  src/components/Home/CgCards/CgCards.js
Labels: level1, gssoc23

#983 Code opimization in features
  src/components/About/Feature.css
  src/components/About/Feature.js
Labels: level2, gssoc23

#982 Server side validation is done
  server/model/Book.js
  server/model/newsletter.js
Labels: level2, gssoc23

#999 Resolving Case Sensitivity-Exploiting Errors Caused by Duplicating Folder Names
  app/api/newsLetter/route.js
  app/api/newsletter/route.js
  model/Newsletter.js
Labels: level1, gssoc23

#948 Mapped the content of Quotes
  src/components/BookList/BookData.js
  src/components/BookList/BookList.js
Labels: level2, gssoc23

#950 Made Footer & Navar buttons Scroll To Top & Minor Changes
  src/components/Footer/Footer.js
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.js
Labels: level2, gssoc23

#1007 Added Responsive Login & Signup page in Next.js13
  app/favicon.ico
  app/login/page.jsx
  app/signup/page.jsx
  components/Navbar/NavItems/NavItems.js
  public/assets/auth/googleLogo.png
  public/assets/auth/login.jpg
  public/assets/auth/signup.jpg
Labels: level2, gssoc23

#1012 [UPDATE] Copy to Clipboard feature Added to Quotes Section
  src/components/BookList/BookList.js
Labels: level2, gssoc23

#1009 Optimize and Refactor: Implement Tailwind CSS for Books, SingleBook, Cookie & Copyright Page.
  app/books/BookList.css
  app/books/Search.jsx
  app/books/Slider.jsx
  app/books/[id]/bookComponent.css
  app/books/[id]/page.jsx
  app/books/page.jsx
  app/cookie/Cookie.css
  app/cookie/page.js
  app/copyright/Copyright.css
  app/copyright/page.js
  next.config.js
Labels: level2, gssoc23

#1010 Optimize and Refactor: Implement Tailwind CSS for Develop, FAQ, Formats and Genre Page.
  app/develop/develop.css
  app/develop/page.jsx
  app/faq/faq.css
  app/faq/page.js
  app/formats/BookFormats.css
  app/formats/bookFormatsData.js
  app/formats/page.js
  app/genre/GenreDetails.css
  app/genre/genreDetailsData.js
  app/genre/page.js
Labels: level2, gssoc23

#1017 faq/section updated
  src/components/FAQ/faq.css
  src/components/FAQ/faq.js
Labels: level1, gssoc23

#1014 Server code fix
  server/app.js
  server/model/Book.js
  server/package-lock.json
  server/package.json
  server/router/book.js
  server/router/contact.js
  server/router/newsletter.js
Labels: help wanted, level2, gssoc23, dependencies

#1025 Inline validation in login/signup
  src/components/Home/BkCards/BkCards.js
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
  src/utils/validation.js
Labels: level2, gssoc23

#1023 added carousel
  src/components/About/Contributor.css
  src/components/About/Contributors.js
Labels: level2, gssoc23

#1019 Updated Book Page with Search Functionality, Copy to Clipboard, Data Fetching with Card Content
  app/api/sendMail/route.js
  app/books/Search.jsx
  app/books/Slider.jsx
  app/books/page.jsx
  components/BkCards/CardContent/CardContent.js
  next.config.js
  public/copyIcon.svg
  utils/Books.js
  utils/bookData.js
Labels: level2, gssoc23

#1031 Add show password Functionality
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
Labels: level1, gssoc23

#1029 Added Next Auth API Route, User Model & Provider Component
  app/api/auth/[...nextauth]/route.js
  app/books/page.jsx
  components/Provider.jsx
  model/User.js
  package-lock.json
  package.json
Labels: level2, gssoc23

#1030 converting pcategories and privacy page code to tailwindcss
  app/pcategories/biography/biography.css
  app/pcategories/biography/page.js
  app/pcategories/career/page.js
  app/pcategories/contemporary/page.js
  app/pcategories/cooking/page.js
  app/pcategories/garden/page.js
  app/pcategories/mystery/page.js
  app/pcategories/politics/page.js
  app/pcategories/science/page.js
  app/pcategories/selfhelp/page.js
  app/pcategories/travel/page.js
  app/privacy/PrivacyPolicy.css
  app/privacy/page.js
Labels: level2, gssoc23

#1033 Add Book Search Functionality and Fix Google Books API Key
  package-lock.json
  package.json
  server/app.js
  server/router/book.js
  src/components/About/Contributors.js
  src/components/Navbar/Navbar.js
  src/utils/searchBooks.js
Labels: good first issue, level3, gssoc23

#1008 hover effect of the logos have been fixed
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
Labels: level1, gssoc23

#1039 revamp: buttons on about us page 🪄
  src/components/About/Download.css
  src/components/About/Download.js
Labels: level1, gssoc23

#1041 fixed positioning in mobile screen
  src/components/Home/ImgSection/ImgSection.js
Labels: level1, gssoc23

#1018 optimizing join page
  app/join/page.js
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.js
  components/join/Benefits.jsx
  components/join/Community.jsx
  components/join/Employee.jsx
  components/join/Header.jsx
  components/join/ImgSection.jsx
  components/join/JobSection.jsx
  public/assets/join/quotationmark.webp
  public/assets/join/workinginoffice.webp
  public/assets/join/workplace.jpeg
  utils/join/benefitsData.js
  utils/join/communityData.js
  utils/join/employeeData.js
  utils/join/positionsData.js
Labels: level2, gssoc23

#1037 Removed prettier workflow from github
  .github/workflows/lint.yml
Labels: level1, gssoc23

#1038 Add-codeql-greetings-file in Next.js 13
  .github/workflows/codeql.yml
  .github/workflows/greetings.yml
Labels: level1, gssoc23

#1050 contributor visibility
  package-lock.json
  package.json
  src/components/About/Contributor.css
  src/components/About/Contributors.js
Labels: level1, gssoc23

#1045 feat: made social anchors accessible on contact us page ✨
  src/pages/Contact/Contactus.js
Labels: level2, gssoc23

#939 Add responsiveness on book page
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
Labels: level2, gssoc23

#1054 feat: made entire terms and services page accessible 🚀
  src/pages/Terms/Terms&Service.js
  src/pages/Terms/TermsAndService.css
Labels: level1, gssoc23

#878 adding link to logo in navbar issue (Issue #817)
  .github/workflows/static.yml
  src/components/Navbar/Navbar.js
Labels: bug, level1, gssoc23

#1055 Prevent Storing of Duplicate Books
  server/controller/book.js
  server/model/Book.js
  server/model/newsletter.js
  src/components/AddBooks/AddBooks.js
  src/components/AddBooks/Upload.js
  src/components/Footer/NewsLetter/NewsLetter.js
  src/utils/impURLs.js
Labels: level2, gssoc23

#1058 Added updated Newsletter, Footer & Constant File
  components/Footer/Footer.css
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.css
  components/Footer/NewsLetter/NewsLetter.js
  next.config.js
  utils/Constants.js
Labels: level2, gssoc23

#1064 Configuring Swagger API into the application
  server/app.js
  server/package-lock.json
  server/package.json
  server/router/book.js
Labels: level3, gssoc23

#1066 Middleware handling
  server/middleware/auth.middlware.js
  server/router/contact.js
  server/router/newsletter.js
  src/components/AddBooks/AddBooks.js
  src/components/AddBooks/Upload.js
  src/components/temp.js
Labels: level2, gssoc23

#1073 Update Server URL and API Keys LIKE GOOGLE_CLIENT_ID and GOOGLE_BOOKS_API_KEY
  package.json
  server/app.js
  server/errors/notfound.js
  src/components/Navbar/Navbar.js
  src/components/Newsletter.js
  src/components/temp.js
  src/index.js
  src/pages/Contact/Contactus.js
  src/pages/Login/GoogleLogin.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Welcomeuser.jsx
  src/utils/searchBooks.js
Labels: level2, gssoc23

#1081 fix: incorrect margin for login with google button on login page 🛠️
  src/pages/Login/Login.jsx
Labels: level1, gssoc23

#1085 📚 Google Book Viewer Integration for Enhanced Informaticon Website 📘🌐
  src/components/Body.js
  src/components/Home/BookComponent/GoogleBookComponent.js
  src/components/Home/Bookpreview/BookPreview.js
  src/components/Navbar/Navbar.js
Labels: good first issue, level3, gssoc23

#1079 Add book form Enhancement
  src/components/AddBooks/AddBooks.css
  src/components/AddBooks/AddBooks.js
  src/components/AddBooks/Upload.css
  src/components/AddBooks/Upload.js
Labels: good first issue, level2, gssoc23

#1077 Made accordion out of the accessibility links
  src/pages/Accessibility/Accessibility.css
  src/pages/Accessibility/Accessibility.js
Labels: level2, gssoc23

#1089 updaing .gitignore file
  .gitignore
Labels: level1, gssoc23

#1092 Removed unnecessary files & updated the Utils Folder
  .dockerignore
  .eslintrc.json
  .github/workflows/codeql.yml
  .github/workflows/lock.yml
  .gitignore
  app/books/page.jsx
  app/contact/page.jsx
  app/pcategories/biography/page.js
  components/Navbar/Navbar.js
  components/join/Benefits.jsx
  components/join/Community.jsx
  components/join/Employee.jsx
  components/join/JobSection.jsx
  utils/Books.js
  utils/Constants.js
  utils/database.js
Labels: level2, gssoc23

#1099 Update layout.jsx
  app/layout.jsx
Labels: level1, gssoc23

#1101 Warning Resolve and Code Improvement
  app/about/page.jsx
  app/faq/faqData.js
  app/faq/page.js
  components/BkCards/BkCards.js
  components/BkCards/CardContent/CardContent.js
  components/Home/CgCards/CgCards.js
  components/Home/CgCards/cardComponentData.js
  components/Navbar/NavItems/NavItems.js
  components/Upload/Upload.js
Labels: level2, gssoc23

#1102 fixing bugs
  app/layout.jsx
  utils/Books.js
Labels: level1, gssoc23

#1100 Updating "How to Install it?" section in Readme.md
  readme.md
Labels: level1, gssoc23

#1106 fixes padding issue in footer
  components/Footer/Footer.js
Labels: level1, gssoc23

#1107 Fix the warning issues & Optimize all files
  app/books/[id]/page.jsx
  app/books/page.jsx
  app/contact/page.jsx
  app/page.jsx
  app/pcategories/biography/page.js
  app/team/Contributors.js
  components/BkCards/CardContent/CardContent.js
  utils/AuthError.js
  utils/Books.js
  utils/Constants.js
  utils/bookData.js
  utils/join/benefitsData.js
  utils/join/communityData.js
  utils/join/employeeData.js
  utils/join/positionsData.js
  utils/validation.js
Labels: level3, gssoc23

#1095 fix: improper footer logo blending with background 🛠
  components/Footer/Footer.js
Labels: invalid

#1129 fix: invisible text on input field during dark mode on login page 🛠️
  app/login/page.jsx
Labels: level1, gssoc23

#1128 feat: revamp quotes section and improved copy quote feature 🚀✨
  app/books/page.jsx
Labels: level1, gssoc23

#1131 fix: Update Footer UI in Footer Section
  components/Footer/Footer.css
  components/Footer/Footer.js
Labels: level1, gssoc23

#1122 Show password Functionality
  app/login/page.jsx
  app/signup/page.jsx
Labels: level2, gssoc23

#1120 feat: add pre-loader animation
  app/layout.jsx
  components/Preloader/Preloader.css
  components/Preloader/Preloader.jsx
Labels: level3, gssoc23

#1115 added login alert fixes issue #1082
  components/Upload/Upload.js
Labels: level1, gssoc23

#1127 fix: aria-label, title, rel, target for Social Icons in Footer Section and Other Minor Bugs in Some Pages
  app/addBooks/page.jsx
  app/books/page.jsx
  app/contact/page.jsx
  app/login/page.jsx
  app/signup/page.jsx
  app/team/Contributors.js
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.js
  components/Navbar/NavItems/NavItems.js
  components/Upload/Upload.js
Labels: level2, gssoc23

#1116 Captcha
  app/login/page.jsx
  app/signup/page.jsx
  public/assets/auth/captcha.webp
Labels: level3, gssoc23

#1113 🚀 Restore Essential Functionalities - Book Search, Google Book Viewer, Google Login 🔧📚
  .gitignore
  app/googlebooks/[bookId]/[isbn]/page.jsx
  app/googlebooks/[bookId]/page.jsx
  app/googlebooks/page.jsx
  app/layout.jsx
  components/Navbar/Navbar.js
  next.config.js
  package-lock.json
  package.json
  utils/searchBooks.js
Labels: level3, gssoc23

#1112 fixing "metadata not recognised" bug
  app/layout.jsx
Labels: level1, gssoc23

#1142 feat: made add books form accessible ✨
  app/addBooks/page.jsx
Labels: level1, gssoc23

#1130 fix bug: display log messages on browser's console
  components/Home/CgCards/CgCards.js
Labels: level1, gssoc23

#1134 Validation in All forms
  app/addBooks/page.jsx
  app/login/page.jsx
  app/signup/page.jsx
  components/Upload/Upload.js
  utils/validation.js
Labels: level3, gssoc23

#1148 updated newsletter submission
  components/Footer/NewsLetter/NewsLetter.js
  package-lock.json
Labels: level1, gssoc23

#1150 [FIX] : 🚀 Automatic Suggestion Dropdown Closure - Improved User Experience 🔧📝
  components/Navbar/Navbar.js
Labels: level1, gssoc23

#1160 Solved All the FrontEnd Issues , Added New Npm Packages
  app/addBooks/page.jsx
  app/books/[id]/page.jsx
  app/contact/page.jsx
  app/googlebooks/[bookId]/page.jsx
  app/googlebooks/page.jsx
  app/layout.jsx
  app/login/page.jsx
  app/signup/page.jsx
  components/BkCards/CardContent/CardContent.js
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.js
  components/Provider.jsx
  components/Upload/Upload.js
  context/AuthContext.jsx
  context/ToasterContext.jsx
  model/User.js
  package-lock.json
  package.json
Labels: level3, gssoc23
