Repository rohansx/informatician, pull requests merged in 2023-06, with the labels that each got.

#374 #366 done
  src/components/Contactus.css
  src/components/Contactus.js
  src/components/faq.css
Labels: bug, GSSOC'23, level2, gssoc23

#377 Fixed Issue #373 - Dragging Carousel Cards Sometimes Selects Text Instead
  src/components/Home/CgCards/CgCards.js
Labels: GSSOC'23, level1, gssoc23

#378 Fixed #372 - Dragging Category Carousel from images shows buggy behaviour
  src/components/Home/CgCards/CardContent/CardContent.js
Labels: GSSOC'23, level1, gssoc23, approved-mentor

#383 #382 added
  src/components/Contactus.js
  src/components/Footer/Footer.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#324 Hamburger menu height issue fixed
  src/components/Navbar/Navbar.css
Labels: GSSOC'23, level2, gssoc23

#402 [Feature] Improve the UI of About us page
  package-lock.json
  src/assets/aboutUs.png
  src/components/About/About.js
Labels: enhancement, GSSOC'23, level2, gssoc23, approved-mentor

#440 Closes #430 and fixes the navbar.css & BookList.js
  src/components/BookList/BookList.js
  src/components/Navbar/Navbar.css
Labels: approved-mentor

#466 App dockerized
  .dockerignore
  Dockerfile
  docker-compose.yml
  server/.dockerignore
  server/Dockerfile
Labels: enhancement, GSSOC'23, level2, gssoc23

#464 Feature : Redesigned Books page and fixed search error
  public/search.png
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
Labels: enhancement, GSSOC'23, level3, gssoc23

#472 bug - UI Home page stretched solved
  package-lock.json
  src/components/Home/BkCards/BkCards.js
Labels: enhancement, GSSOC'23, level1, gssoc23

#479 Books loading issue resolved
  package-lock.json
  src/components/BookList/BookList.js
  src/utils/searchBooks.js
Labels: enhancement, GSSOC'23, level3, gssoc23

#483 Bug - Solved the height of the book card not proper on hover
  src/components/Footer/NewsLetter/NewsLetter.js
  src/components/Home/BkCards/BkCards.css
  src/components/Home/BkCards/BkCards.js
  src/components/Home/BkCards/CardContent/CardContent.css
  src/components/Home/BkCards/CardContent/CardContent.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#516 #331 Refine added
  package-lock.json
  package.json
  src/App.js
Labels: enhancement, GSSOC'23, level3, gssoc23

#522 #521 fixed
  src/components/Home/SingleBk/SingleBk.js
  src/components/Home/SingleBk/SingleBk1.js
  src/components/Home/SingleBk/SingleBk2.js
  src/components/Home/SingleBk/SingleBk3.js
  src/components/Home/SingleBk/SingleBk4.js
  src/components/Home/SingleBk/SingleBk5.js
  src/components/Home/SingleBk/SingleBk6.js
  src/components/Home/SingleBk/SingleBk7.js
  src/components/Home/SingleBk/SingleBk8.js
  src/components/Home/SingleBk/SingleBk9.js
Labels: bug, GSSOC'23, level2, gssoc23

#541 #540 changed
  src/components/Cookie.js
  src/components/PrivacyPolicy.js
  src/components/Terms&Service.js
Labels: GSSOC'23, level1, gssoc23

#562 fixed bug in books page search bar
  src/components/BookList/BookList.css
Labels: GSSOC'23, level1, gssoc23

#576 Dark mode added to Terms and Cookies pages with minor issues resolved
  src/components/Body.js
  src/components/Cookie.css
  src/components/Terms&Service.js
  src/components/TermsAndService.css
Labels: enhancement, GSSOC'23, level2, gssoc23

#582 Added Website Loader
  public/index.html
Labels: GSSOC'23, level1, gssoc23

#579 Solved all the dark mode issues - Our Team | Privacy Policy | Books
  src/components/Body.js
  src/components/Home/SingleBk/SingleBk.js
  src/components/Home/SingleBk/SingleBk1.js
  src/components/Home/SingleBk/SingleBk2.js
  src/components/Home/SingleBk/SingleBk3.js
  src/components/Home/SingleBk/SingleBk4.js
  src/components/Home/SingleBk/SingleBk5.js
  src/components/Home/SingleBk/SingleBk6.js
  src/components/Home/SingleBk/SingleBk7.js
  src/components/Home/SingleBk/SingleBk8.js
  src/components/Home/SingleBk/SingleBk9.js
  src/components/Team/ContCard.js
  src/components/Team/Contributor.css
  src/components/Team/Contributor.js
  src/components/Team/Team.js
Labels: GSSOC'23, level2, gssoc23

#589 Enhance contact us
  src/components/Contactus.css
  src/components/Contactus.js
Labels: enhancement, GSSOC'23, level1, gssoc23

#588 Added dark mode to FAQs
  src/components/Body.js
  src/components/faq.js
Labels: enhancement, GSSOC'23, level1, gssoc23

#591 Added the Copyright page
  src/components/Body.js
  src/components/Copyright/Copyright.css
  src/components/Copyright/Copyright.js
  src/components/Footer/Footer.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#594 Added the Accessibility page
  src/components/Accessibility/Accessibility.css
  src/components/Accessibility/Accessibility.js
  src/components/Body.js
  src/components/Footer/Footer.js
Labels: GSSOC'23, level2, gssoc23

#596 #595 Added
  .github/workflows/goosc label.yml
Labels: level2, gssoc23

#613 issue #605 Reading Challenge and Progress Tracking
  package-lock.json
  src/assets/ProgressTracking.jpg
  src/assets/ebooks/ReadingChallenge.png
  src/components/About/Feature.js
Labels: enhancement, level1, gssoc23

#614 UI Improvement
  src/components/Navbar/Navbar.js
Labels: level1, gssoc23

#619 Added hover effects to the links in the footer
  src/components/Footer/Footer.js
Labels: level1, gssoc23

#620 Switched all color codes to css variables.
  src/App.js
  src/components/About/About.css
  src/components/About/About.js
  src/components/About/Feature.js
  src/components/About/Testimonial.css
  src/components/About/Testimonial.js
  src/components/Accessibility/Accessibility.css
  src/components/Accessibility/Accessibility.js
  src/components/Body.js
  src/components/BookList/BookList.css
  src/components/Contactus.css
  src/components/Contactus.js
  src/components/Cookie.css
  src/components/Cookie.js
  src/components/Copyright/Copyright.css
  src/components/Copyright/Copyright.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/NewsLetter/NewsLetter.css
  src/components/Home/BkCards/CardContent/CardContent.css
  src/components/Navbar/Navbar.css
  src/components/PrivacyPolicy.css
  src/components/PrivacyPolicy.js
  src/components/Team/ContCard.js
  src/components/Team/Contributor.css
  src/components/Team/Team.css
  src/components/Team/Team.js
  src/components/Terms&Service.js
  src/components/TermsAndService.css
  src/components/faq.js
  src/index.css
Labels: level2, gssoc23

#617 Update BookList.css
  src/components/BookList/BookList.css
Labels: level2, gssoc23

#623 Added lazy loading
  src/components/Body.js
Labels: level2, gssoc23

#624 Changed the alignment of testimonials
  package-lock.json
  src/components/About/Testimonial.css
  src/components/About/Testimonial.js
Labels: level2, gssoc23

#627 [BUG] Fixed issue #601 which was not showing the text properly
  package-lock.json
  src/components/BookList/BookList.css
Labels: level1, gssoc23

#629 Contact us page updated
  src/components/Contactus.css
  src/components/Contactus.js
Labels: level1, gssoc23

#631 Added the Publishers Page
  src/components/Body.js
  src/components/Footer/Footer.js
  src/components/Publishers/Publishers.css
  src/components/Publishers/Publishers.jsx
Labels: level2, gssoc23

#641 Solved the dark mode issue on Develop page
  src/components/develop.css
  src/components/develop.js
Labels: level1, gssoc23

#644 Added the AdChoices page
  src/components/AdChoices/AdChoices.css
  src/components/AdChoices/AdChoices.js
  src/components/Body.js
  src/components/Footer/Footer.js
  src/components/Publishers/Publishers.jsx
Labels: level2, gssoc23

#647 #570 page designed
  .github/workflows/goosc label.yml
  package-lock.json
  package.json
  src/components/Categories/biography.css
  src/components/Categories/biography.js
Labels: level3, gssoc23

#651 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: level1, gssoc23

#643 About us enhancement 👍
  src/components/About/About.css
  src/components/About/About.js
  src/components/About/Feature.css
  src/components/About/Feature.js
  src/components/About/Testimonial.css
  src/components/About/Testimonial.js
Labels: level2, gssoc23

#669 fixed issue
  src/components/BookList/BookList.css
Labels: level1, gssoc23

#668 Fix testimonial
  src/components/About/Testimonial.css
  src/components/About/Testimonial.js
Labels: level2, gssoc23

#673 Fixed Card UI in Slider
  src/components/Home/BkCards/BkCards.css
Labels: level1, gssoc23

#679 UI Fixed
  src/components/Navbar/Navbar.js
Labels: level1, gssoc23

#691 Enhanced feature section
  src/components/About/About.js
  src/components/About/Feature.css
  src/components/About/Feature.js
Labels: level2, gssoc23

#695 Added sitemap.xml for SEO
  public/sitemap.xml
Labels: level2, gssoc23

#696 Added More Books
  src/assets/career/money.jpeg
  src/assets/career/monk.webp
  src/assets/ebooks/atomic-habits.webp
  src/assets/ebooks/starts-with-us.jpeg
  src/assets/selfHelp/alchemist.jpg
  src/components/Body.js
  src/components/Home/SingleBk/SingleBk10.js
  src/components/Home/SingleBk/SingleBk11.js
  src/components/Home/SingleBk/SingleBk12.js
  src/components/Home/SingleBk/SingleBk13.js
  src/components/Home/SingleBk/SingleBk14.js
Labels: level2, gssoc23

#701 books page css modified
  src/components/BookList/BookList.css
Labels: level1, gssoc23

#698 Name Logo of the Website
  src/assets/logos/dark_logo.png
  src/assets/logos/light_logo.png
  src/components/Footer/Footer.js
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
Labels: level2, gssoc23

#702 UI/UX Improvement
  src/components/JoinOurTeam/Join.js
Labels: level2, gssoc23

#703 Category
  server/controller/book.js
  server/model/Book.js
  server/router/book.js
  src/components/AddBooks/AddBooks.js
Labels: level2, gssoc23

#704 UI of categories section updated
  src/components/Home/CgCards/CardContent/CardContent.css
  src/components/Home/CgCards/CardContent/CardContent.js
  src/components/Home/CgCards/CgCards.js
Labels: level2, gssoc23

#724 Issue resolved #650 quotes hover section
  src/components/BookList/BookList.css
  src/components/Card.css
Labels: level2, gssoc23

#725 Old changes overlay new.
  src/components/About/Feature.css
  src/components/About/Feature.js
  src/components/About/Testimonial.css
  src/components/About/Testimonial.js
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
  src/components/Home/CgCards/CgCards.js
Labels: level2, gssoc23

#727 Biography page updated
  src/components/Body.js
  src/components/Categories/biography.css
  src/components/Categories/biography.js
Labels: level2, gssoc23

#736 Added the page - Book Formats
  src/assets/Formats/audiobook.webp
  src/assets/Formats/comics.webp
  src/assets/Formats/ebook.jpeg
  src/assets/Formats/magazines.jpg
  src/assets/Formats/paperback.webp
  src/components/Body.js
  src/components/BookFormats/BookFormats.css
  src/components/BookFormats/BookFormats.js
  src/components/Footer/Footer.js
Labels: level2, gssoc23

#737 Added Genre Explore Page
  src/assets/Genre/biography.webp
  src/assets/Genre/horror.jpg
  src/assets/Genre/mystery.jpg
  src/assets/Genre/romance.webp
  src/assets/Genre/science.jpg
  src/assets/Genre/thriller.webp
  src/components/Body.js
  src/components/Footer/Footer.js
  src/components/GenreDetails/GenreDetails.css
  src/components/GenreDetails/GenreDetails.js
Labels: level2, gssoc23

#743 cards updated
  src/components/BookList/BookList.css
Labels: level1, gssoc23

#746 Fixed the icon visibility issue
  src/components/AddBooks/AddBooks.css
Labels: level1, gssoc23

#752 added smooth hovering to cards
  src/components/Home/BkCards/BkCards.css
  src/components/Home/BkCards/CardContent/CardContent.css
Labels: level2, gssoc23

#754 Added some hover effects to top scroll button
  src/components/ScrollButton.css
Labels: level1, gssoc23

#756 Added some transition effects on contact us pic
  src/components/Contactus.css
Labels: level1, gssoc23

#757 Added Lazy loading to all the images
  src/components/About/About.js
  src/components/About/Download.js
  src/components/About/Testimonial.js
  src/components/Benefits/Benefits.js
  src/components/BookFormats/BookFormats.js
  src/components/BookList/BookList.js
  src/components/Bookmarks/BookmarkPage.js
  src/components/Card.js
  src/components/Contactus.js
  src/components/Error.js
  src/components/Footer.js
  src/components/Footer/Footer.js
  src/components/GenreDetails/GenreDetails.js
  src/components/Home/BkCards/CardContent/CardContent.js
  src/components/Home/CgCards/CardContent/CardContent.js
  src/components/Home/SingleBk/SingleBk.js
  src/components/Home/SingleBk/SingleBk1.js
  src/components/Home/SingleBk/SingleBk10.js
  src/components/Home/SingleBk/SingleBk11.js
  src/components/Home/SingleBk/SingleBk12.js
  src/components/Home/SingleBk/SingleBk13.js
  src/components/Home/SingleBk/SingleBk14.js
  src/components/Home/SingleBk/SingleBk2.js
  src/components/Home/SingleBk/SingleBk3.js
  src/components/Home/SingleBk/SingleBk4.js
  src/components/Home/SingleBk/SingleBk5.js
  src/components/Home/SingleBk/SingleBk6.js
  src/components/Home/SingleBk/SingleBk7.js
  src/components/Home/SingleBk/SingleBk8.js
  src/components/Home/SingleBk/SingleBk9.js
  src/components/JoinOurTeam/Join.js
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.js
  src/components/Team/ContCard.js
  src/components/Team/Team.js
  src/components/develop.js
  src/components/faq.js
Labels: level2, gssoc23
