Repository rohansx/informatician, pull requests merged in 2023-08, with the labels that each got.

#1163 Same form for book data and book info
  app/addBooks/page.jsx
  components/Upload/Upload.js
Labels: level3, gssoc23

#1167 🚀 Dynamic New York Times Best Sellers Integration - Enhanced User Experience 🔧📚
  app/layout.jsx
  app/page.jsx
  components/TNYCards/BkCards.js
  components/TNYCards/CardContent/CardContent.js
  components/TNYCards/Spinner.css
  next.config.js
  package-lock.json
  package.json
Labels: level3, gssoc23

#1179 Fixed Font Color for Email and Password Input Fields
  app/login/page.jsx
Labels: level1, gssoc23

#1180 fix: lack of paddings for footer on mobile devices ⚒️
  components/Footer/Footer.js
Labels: level1, gssoc23

#1181 fix: wrong contributing guidelines documentation link on bug issue template ⚒️
  .github/ISSUE_TEMPLATE/bug.yml
Labels: level1, gssoc23

#1162 Added NextAuth API Routes & PrismaDB
  app/api/auth/[...nextauth]/route.js
  app/api/register/route.jsx
  libs/prismadb.jsx
  prisma/schema.prisma
Labels: level3, gssoc23

#1182 fix: bad contrast color applied for headings on faq page ⚒️
  components/Footer/Footer.css
Labels: level1, gssoc23

#1189 🚀 Dynamic Famous Quotes Integration - Inspire and Motivate Users 🔧💬
  app/books/Spinner.css
  app/books/page.jsx
  components/Quotes/Card.jsx
  model/User.js
  package-lock.json
  package.json
Labels: level3, gssoc23

#1204 improved quote section
  app/books/page.jsx
  components/Quotes/Card.jsx
  package-lock.json
Labels: level1, gssoc23

#1188 Upload book cross icon
  components/Upload/Upload.js
Labels: level1, gssoc23

#1214 fix: missaligned copyright and it's elements on footer ⚒️✨
  components/Footer/Footer.js
Labels: level1, gssoc23

#1208 fix: bad contrast color for contributors details on team page ⚒️✨
  app/team/Contributors.js
Labels: level1, gssoc23

#1216 Added Fully Functional NextAuth Authentication
  app/api/auth/[...nextauth]/route.js
  app/api/register/route.js
  app/login/page.jsx
  app/signup/page.jsx
  components/Navbar/NavItems/NavItems.js
  components/Navbar/Navbar.js
  package-lock.json
  package.json
  utils/database.js
Labels: level3, gssoc23

#1213 fix: incorrect placement of theme toggle button on mobile ⚒️ ✨
  components/theme/theme-toggle.jsx
Labels: level1, gssoc23

#1201 Added twitter to the testimonials section
  components/About/Testimonial.js
Labels: level1, gssoc23

#1215 Added new feature of bookmark with useState for remove button
  app/bookmark/page.jsx
  app/books/page.jsx
  app/googlebooks/[bookId]/[isbn]/page.jsx
  components/TNYCards/BkCards.js
  package-lock.json
Labels: level3, gssoc23

#1224 Added more quotes Fixes #931
  utils/Constants.js
Labels: level1, gssoc23

#1161 unwanted console.log removed
  components/Footer/NewsLetter/NewsLetter.js
  components/Navbar/Navbar.js
Labels: level1, gssoc23

#1196 Addition of Hover Effect on Subscribe button
  components/Footer/NewsLetter/NewsLetter.css
Labels: level1, gssoc23

#1152 fixed issue : About Us Section Doesn't Mention Anywhere the name of t…
  app/about/page.jsx
Labels: level1, gssoc23

#1154 Align the underline in the middle in navbar
  components/Navbar/Navbar.css
Labels: level1, gssoc23

#1203 fix: Added styles.yml , documentation.yml Files for Issue Templates
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/styles.yml
Labels: level2, gssoc23

#1231 Dark Mode is now Applied to Newsletter Component ✨
  app/layout.jsx
  app/page.jsx
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.css
Labels: level2, gssoc23

#1233 Changes in Features
  app/about/page.jsx
  components/About/Feature.css
  components/About/Testimonial.js
Labels: level1, gssoc23

#1235 removing bg-white for better ui in dark mode
  app/formats/page.js
  components/Navbar/NavItems/NavItems.js
Labels: level1, gssoc23

#1236 updating screenshot section in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: level1, gssoc23

#1239 converting css into tailwindcss for footer, publisher, team and terms page.
  app/adchoices/page.jsx
  app/layout.jsx
  app/page.jsx
  app/publishers/Publishers.css
  app/publishers/page.jsx
  app/team/Contributors.js
  app/team/Team.css
  app/team/page.jsx
  app/terms/TermsAndService.css
  app/terms/page.js
  components/Footer/Footer.css
  components/Footer/Footer.js
  context/ToasterContext.jsx
Labels: level2, gssoc23

#1230 Icons in Form Field
  app/contact/page.jsx
  app/login/page.jsx
  app/signup/page.jsx
  utils/validation.js
Labels: level1, gssoc23

#1245 making route components as server
  app/about/page.jsx
  app/addBooks/AddBooks.jsx
  app/addBooks/page.jsx
  app/awards/BookAward.jsx
  app/awards/page.js
  app/benefits/page.js
  app/bookmark/Bookmark.jsx
  app/bookmark/page.jsx
  app/books/BookList.jsx
  app/books/[id]/page.jsx
  app/books/page.jsx
  app/contact/Contact.jsx
  app/contact/page.jsx
  app/faq/Accordion.jsx
  app/faq/page.js
  app/formats/SBook.jsx
  app/formats/page.js
  app/genre/SGenre.jsx
  app/genre/page.js
  app/googlebooks/page.jsx
  app/login/Login.jsx
  app/login/page.jsx
  app/pcategories/biography/Biography.jsx
  app/pcategories/biography/page.js
  app/signup/Signup.jsx
  app/signup/page.jsx
  app/team/Team.jsx
  app/team/page.jsx
  components/About/Feature.js
  components/About/Hero.jsx
  components/RStar.jsx
Labels: level3, gssoc23

#1251 FIxed form errors and eye icon
  app/login/Login.jsx
  package-lock.json
Labels: level1, gssoc23

#1248 Dynamic Page Titles for Improved User Experience and Branding
  app/about/page.jsx
  app/accessibility/page.jsx
  app/adchoices/page.jsx
  app/addBooks/AddBooks.jsx
  app/addBooks/page.jsx
  app/awards/page.js
  app/benefits/page.js
  app/bookmark/page.jsx
  app/books/[id]/page.jsx
  app/books/page.jsx
  app/contact/page.jsx
  app/cookie/page.js
  app/copyright/page.js
  app/develop/page.jsx
  app/faq/page.js
  app/formats/page.js
  app/genre/page.js
  app/join/page.js
  app/login/page.jsx
  app/metadata.js
  app/pcategories/biography/page.js
  app/privacy/page.js
  app/publishers/page.jsx
  app/signup/page.jsx
  app/team/page.jsx
  app/terms/page.js
Labels: level2, gssoc23

#1217 Quote Section Content Position Correction
  components/Footer/NewsLetter/NewsLetter.css
  components/Quotes/Card.jsx
  styles/globals.css
Labels: level1, gssoc23

#1237 improved the footer topics UI
  app/page.jsx
  components/Footer/Footer.js
Labels: level1, gssoc23

#1238 Highlighted button text
  components/Footer/NewsLetter/NewsLetter.css
Labels: level1, gssoc23

#1253 'Our Core Team' Section Content Alignment
  components/About/Testimonial.js
  styles/globals.css
Labels: level1, gssoc23

#1256 Adding package-lock.json to .gitignore
  .gitignore
  package-lock.json
Labels: level1, gssoc23

#1261 Fixed Contact API URL
  app/contact/Contact.jsx
  components/Footer/NewsLetter/NewsLetter.js
  package.json
Labels: level1, gssoc23

#1259 feat: added dynamic routing in all the genre sub page
  app/formats/SBook.jsx
  app/formats/[slug]/page.js
  app/formats/bookFormatsData.js
  app/formats/page.js
  app/genre/SGenre.jsx
  app/genre/[slug]/page.js
  app/genre/genreDetailsData.js
  app/genre/page.js
  components/Icons.js
  package.json
Labels: level2, gssoc23

#1255 Adding Loading Animation to website
  app/layout.jsx
  app/login/page.jsx
  components/Preloader/Preloader.css
  components/Preloader/Preloader.jsx
Labels: level3, gssoc23

#1218 Random positioning of Search Area in Book section
  app/books/Spinner.css
  app/books/page.jsx
Labels: level1, gssoc23

#1268 #1267 code formatted
  app/layout.jsx
  app/metadata.js
  app/signup/Signup.jsx
  app/team/Contributors.js
  app/team/Team.jsx
  app/team/page.jsx
  components/About/Download.js
  components/About/Feature.css
  components/About/Feature.js
  components/About/Hero.jsx
  components/About/Testimonial.js
  components/BkCards/BkCards.js
  components/BkCards/CardContent/CardContent.js
  components/DataProvider.js
  components/Footer/Footer.js
  components/Footer/NewsLetter/NewsLetter.css
  components/Footer/NewsLetter/NewsLetter.js
  components/Home/CgCards/CardContent/CardContent.css
  components/Home/CgCards/CardContent/CardContent.js
  components/Home/CgCards/CgCards.js
  components/Home/CgCards/cardComponentData.js
  components/Home/ImgSection/AutoType.jsx
  components/Home/ImgSection/ImgSection.css
  components/Home/ImgSection/ImgSection.js
  components/Icons.js
  components/Logo.js
  components/Navbar/NavItems/NavItems.js
  components/Navbar/Navbar.css
  components/Navbar/Navbar.js
  components/Preloader/Preloader.css
  components/Preloader/Preloader.jsx
  components/Quotes/Card.jsx
  components/RStar.jsx
  components/ScrollButton/ScrollButton.css
  components/ScrollButton/ScrollButton.js
  components/TNYCards/CardContent/CardContent.js
  components/Upload/Upload.js
  components/join/Benefits.jsx
  components/join/Community.jsx
  components/join/Employee.jsx
  components/join/Header.jsx
  components/join/ImgSection.jsx
  components/join/JobSection.jsx
  components/theme/theme-provider.jsx
  components/theme/theme-toggle.jsx
  context/AuthContext.jsx
  libs/prismadb.jsx
  model/Book.js
  model/Newsletter.js
  model/User.js
  styles/CardContent.module.css
  styles/SingleBK.css
  styles/globals.css
  utils/Constants.js
  utils/database.js
  utils/searchBooks.js
  utils/validation.js
Labels: level3, gssoc23

#1271 #1270 designed
  pages/404.js
  public/error.png
Labels: level2, gssoc23

#1273 #1272 added
  app/genre/genreDetailsData.js
  public/assets/Genre/adventure.jpeg
  public/assets/Genre/fantasy.jpeg
  public/assets/Genre/historical.jpeg
Labels: level1, gssoc23

#1275 #1274 fixed
  app/faq/Accordion.jsx
Labels: level1, gssoc23

#1269 Preview of Book Cover Image
  app/addBooks/AddBooks.jsx
Labels: level2, gssoc23

#1276 Update readme.md
  readme.md
Labels: level1, gssoc23

#1266 Feature-Improvement
  components/About/Feature.css
  components/About/Feature.js
Labels: level2, gssoc23
