Repository rohansx/informatician, pull requests merged in 2023-05, with the labels that each got.

#40 #39 done
  package-lock.json
  package.json
  src/App.js
  src/components/Navbar.css
  src/components/Navbar.js
Labels: GSSoC

#70 Change: Bootstrap on Navbar
  public/index.html
  src/App.css
  src/App.js
  src/Home.js
  src/components/Body.js
  src/components/BookList.css
  src/components/BookList.js
  src/components/Home.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/index.css
Labels: good first issue, GSSoC, GSSoC'23

#126 #120 done
  src/components/Body.js
  src/components/PrivacyPolicy.css
  src/components/PrivacyPolicy.js
Labels: GSSoC'23

#127 #121 done
  src/components/Body.js
  src/components/Cookie.css
  src/components/Cookie.js
Labels: GSSoC, GSSoC'23

#128 #118 done
  src/assets/help.png
  src/components/Body.js
  src/components/Footer.js
  src/components/faq.css
  src/components/faq.js
Labels: GSSoC'23

#155 Update README.md
  README.md
Labels: documentation, good first issue, GSSoC, GSSoC'23, level1

#159 (#130) Subscribe to Newsletter
  .gitignore
  server/.env
  server/app.js
  server/controller/newsletter.js
  server/model/newsletter.js
  server/package-lock.json
  server/package.json
  server/router/newsletter.js
  src/components/Footer.js
  src/components/Newsletter.js
Labels: GSSoC

#168 #166 fixed
  src/components/Navbar.css
  src/components/Navbar.js
Labels: GSSoC, GSSoC'23

#192 #189 done
  src/assets/construct.png
  src/components/Body.js
  src/components/develop.js
Labels: GSSoC, GSSoC'23

#198 #197 done
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
Labels: GSSoC'23, gssoc23

#201 Depandabot added
  .github/dependabot.yml
Labels: GSSoC'23, level1, gssoc23

#207 fixed navbar display flex that was overwritten by some other style
  src/components/Navbar/Navbar.css
Labels: enhancement, GSSoC'23, level1, gssoc23

#218 #214 fixed
  src/components/Navbar/Navbar.js
Labels: enhancement, GSSoC'23, level1, gssoc23

#220 Book search functionality added along with responsiveness
  src/components/BookList/BookList.css
  src/components/BookList/BookList.js
  src/components/Card.css
  src/components/Card.js
Labels: enhancement, GSSoC'23, level2, gssoc23

#225 #216 fixed
  src/components/Navbar/Navbar.js
Labels: bug, GSSoC'23, level3, gssoc23

#230 #229 done
  package-lock.json
  package.json
  src/assets/giphy.gif
  src/components/About/About.css
  src/components/About/About.js
Labels: bug, enhancement, GSSoC'23, level2, gssoc23

#234 Bug Fixed - Responsive Navbar Now
  public/index.html
  src/components/Home/ImgSection/ImgSection.js
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
Labels: enhancement, GSSoC'23, level1, gssoc23

#250 #249 custom page designed and linked
  src/components/Footer/Footer.js
  src/components/develop.js
Labels: enhancement, GSSOC'23, level2

#235 change the footer done issue #199
  package-lock.json
  src/App.js
  src/components/Footer/Footer.js
  src/index.css
Labels: enhancement, GSSOC'23, level2, gssoc23

#256 Fix of footer buttons not scrolling to top
  package-lock.json
  src/components/Footer/Footer.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#261 Enhanced the scrollbar
  src/index.css
Labels: enhancement, GSSOC'23, level2, gssoc23

#257 pause autoplay when mouse over the book cards
  src/components/Home/BkCards/BkCards.js
Labels: enhancement, GSSOC'23, level1, gssoc23

#276 Formated navbar according to theme
  src/assets/icon.png
  src/components/Footer/Footer.js
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#289 [Fixed]: change color of submit button, social icons on contact page issue #241
  src/components/Contactus.css
  src/components/Contactus.js
Labels: enhancement, GSSOC'23, level1, gssoc23

#295 #292 done
  src/components/Footer/Footer.js
Labels: bug, GSSOC'23, level1, gssoc23

#306 Removed the add book option from navbar
  package-lock.json
  src/components/Navbar/NavItems/NavItems.js
  src/components/Navbar/Navbar.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#309 Fixes CSSValidation errors
  package-lock.json
  src/components/Home/BkCards/CardContent/CardContent.css
Labels: GSSOC'23, level1, gssoc23

#307 #231 done
  .gitignore
  server/.env
  server/app.js
  server/package-lock.json
  server/package.json
Labels: enhancement, GSSOC'23, level3, gssoc23

#310 Alignment solved on the Contact Us page
  src/components/Contactus.css
  src/components/Contactus.js
Labels: GSSOC'23, level1, gssoc23

#312 FAQ Header alignment
  src/components/faq.css
Labels: GSSOC'23, level1, gssoc23

#314 Setup SMTP server for Contact Form
  server/.env
  server/app.js
  server/router/contact.js
  src/components/Contactus.js
Labels: enhancement, GSSOC'23, level3, gssoc23

#321 #285 Add runtime.js file to resolve module import error in Mac and Linux Systems
  src/runtime.js
Labels: bug, GSSOC'23, level3, gssoc23

#320 Update readme.md
  readme.md
Labels: enhancement, GSSOC'23, level1, gssoc23

#327 Added home route redirection on clicking footer logo
  src/components/Footer/Footer.js
Labels: level1, gssoc23

#333 Update readme.md
  readme.md
Labels: documentation, GSSOC'23, level1, gssoc23

#332 Update close_old_issues.yaml
  .github/workflows/close_old_issues.yaml
Labels: documentation, GSSOC'23, level1, gssoc23

#343 Added Category section to Home page
  package-lock.json
  package.json
  src/components/Home/BkCards/CardContent/CardContent.css
  src/components/Home/CgCards/CardContent/CardContent.css
  src/components/Home/CgCards/CardContent/CardContent.js
  src/components/Home/CgCards/CgCards.js
  src/components/Home/Home.js
Labels: enhancement, GSSOC'23, level3, gssoc23

#345 Added Download Section
  src/assets/logo.png
  src/assets/mobile.png
  src/components/About/About.js
  src/components/About/Download.css
  src/components/About/Download.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#350 Update bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: documentation, GSSOC'23, level1, gssoc23

#351 Update feature_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, GSSOC'23, level1, gssoc23

#349 #348 done
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
Labels: bug, GSSOC'23, level2, gssoc23

#359 RESOLVED #242 : Enhanced the FAQ page
  src/components/faq.css
  src/components/faq.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#360 Animation added to screen to top button.
  src/components/ScrollButton.css
  src/components/ScrollButton.js
Labels: enhancement, GSSOC'23, level1, gssoc23

#363 Cards Size Enhanced
  src/components/Home/BkCards/CardContent/CardContent.js
Labels: enhancement, GSSOC'23, level2, gssoc23

#369 Category Cards Carousel Infinite Loop Fixed
  package-lock.json
  src/components/Home/CgCards/CgCards.js
Labels: bug, GSSOC'23, level1, gssoc23

#371 Fixed Issue #370
  src/components/Home/CgCards/CgCards.js
Labels: enhancement, GSSOC'23, level1, gssoc23
